# Welcome to Jekyll!
#

# Site settings
title: Gentle Birth Care
owner: Gentle Birth Care # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>

   
collections:
  midwives:
    output: true
  assistants:
    output: true


defaults:
  -
    scope:
      path: ""
      type: "midwives"
    values:
      layout: "midwife-layout"
  -
    scope:
      path: ""
      type: "assistants"
    values:
      layout: "assistants-layout"


# Build settings
markdown: kramdown
